# name: Jest Testing

# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]

# jobs:
#   jest:
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: mobile

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Run Jest
#         run: npm run test:coverage

#       - name: Upload Jest coverage
#         if: success()
#         uses: actions/upload-artifact@v4
#         with:
#           name: jest-coverage
#           path: mobile/coverage/lcov.info
#           if-no-files-found: warn
